"use strict";
const labels={programming:"程式語言","ai-llm":"AI 與開源 LLM",hardware:"電腦硬體零組件"};
let items=[],category="all";
const grid=document.querySelector("#newsGrid"),search=document.querySelector("#search"),tabs=document.querySelector("#tabs"),empty=document.querySelector("#empty"),error=document.querySelector("#error");
function dateText(v){if(!v)return"時間未提供";const d=new Date(v);return Number.isNaN(d.getTime())?v:new Intl.DateTimeFormat("zh-TW",{month:"2-digit",day:"2-digit",hour:"2-digit",minute:"2-digit"}).format(d)}
function safeUrl(v){try{const u=new URL(v);return["http:","https:"].includes(u.protocol)?u.href:"#"}catch{return"#"}}
function makeCard(n){const a=document.createElement("article");a.className="card";a.dataset.category=n.category;const tag=document.createElement("span");tag.className="tag";tag.textContent=labels[n.category]||n.category;const h=document.createElement("h3");h.textContent=n.title||"";const p=document.createElement("p");p.className="summary";p.textContent=n.summary||"";const f=document.createElement("div");f.className="foot";const s=document.createElement("span");s.textContent=(n.source||"來源未提供")+" · "+dateText(n.publishedAt);const link=document.createElement("a");link.href=safeUrl(n.url);link.target="_blank";link.rel="noopener noreferrer";link.textContent="原文 ↗";f.append(s,link);a.append(tag,h,p,f);return a}
function render(){const q=search.value.trim().toLocaleLowerCase("zh-Hant-TW");const shown=items.filter(n=>(category==="all"||n.category===category)&&(!q||((n.title||"")+" "+(n.summary||"")+" "+(n.source||"")).toLocaleLowerCase("zh-Hant-TW").includes(q)));grid.replaceChildren(...shown.map(makeCard));empty.hidden=shown.length!==0;document.querySelector("#resultMeta").textContent="顯示 "+shown.length+" / "+items.length+" 則"}
tabs.addEventListener("click",e=>{const b=e.target.closest("[data-category]");if(!b)return;category=b.dataset.category;tabs.querySelectorAll("button").forEach(x=>x.classList.toggle("active",x===b));render()});search.addEventListener("input",render);
(async()=>{try{const r=await fetch("./data/news.json",{cache:"no-store"});if(!r.ok)throw new Error(r.status);const d=await r.json();items=Array.isArray(d.items)?d.items:[];document.querySelector("#newsCount").textContent=String(items.length);document.querySelector("#updatedAt").textContent=d.updatedAt?new Intl.DateTimeFormat("zh-TW",{year:"numeric",month:"2-digit",day:"2-digit",hour:"2-digit",minute:"2-digit"}).format(new Date(d.updatedAt)):"尚未更新";render()}catch(e){console.error(e);error.hidden=false}})();